env:
  global:
  - COMPONENT=front
  - TOOLS_DIR=$HOME/tools
  - PATH=$TOOLS_DIR/bin:$PATH
  - secure: EMCXP/t2rBDNvuJnvZflZIQnoi+YUR2Df4KmbFtV7KCbx7EmZO1JGBmfn1guXxUmASWYAU3iUnnOEd+v3nket12M89BxaX8RMaKb2re1qBnXb0SgFoU0hSi4Bt/DYSczG7qvxTr7eTow9isbY0i5rY3FU24/w3AHEVemx6kq8lF3TC86Fz7yHDq8eW+dkbgoDltaCh4REGs5m3KRVeBuQlOg4h7+L9N4by29phAOXkE1zmcDMPR74RIadCRXW8uKvwfhO8lW5CWh52xymi05WjJFkWVqkrXMU5swm+EbAauMHfv6F9LiStmcvoHfFqk7ichDPS54V1magXcSdRr8ElMmg8vWmCieUg++SFUSrFjM0k/ReK/GnNNal5SWP4OoDdkt9SlaKfhWPMrWwxXAIZHgL1AVMJJZP7aXg18e7KW5b2rW67XxvmA6Oe1aZQO75Hdk8ooGHtHw3XcuCL1MTHfb24XRpHcswAEQUjVe+0ZiGj08XXAiiwdFVkq6TIyvc42hRs6ngfxRSraBWj7WxkjJkdPRhAh/3OQL87aWBAVJ+zRcwhLBDx6REmzu6SM4g452UGVfsbp1kHLF+HQNRfUEfXpXwavp3JWZdt4EIc+R1mnJr0tVMNMkeQr7A5DDisDDsiJo5kw4MV4+vhYLfKxQgS3sl8p74cFdeGX2jKc=
  - secure: YRthpcDntUDqkk6wGDPTrzt/8Ul97OivA+9F0UvFMWRg99ax+iLIh8oYxHACBL8XH/8aJY6J7v4tNMt5uCLIKnltIHAVBseIOGd8reWWzuweXVRj9QD1bRRWendAVR43ZxM+BEZIkbsVZt/5Lll9selXQlFFsLmS7cflA1Jed8iNhJvNd5r8YM7MEDXnspSDdtFaRCzJhhaJ2t/9hrezWjMQpaSJG9XHkwAGBtc+uemNlFQnKmtuj5BY8Q6CdlNIKELXqGwb7YiGgBeC+UlewN2wJYQ/78hapZF9AVrk67fe491uKaca97OY0GAXgOlIxAJC1VZjyGSgEdsvpIRaYcq3NPMwrlnCivQe9iWGWx9TFBHGgrtXjV1Bcbg55g/B82O+OhbbcZic0bpfRdWy0wr59Q3RKgOEkiArmRGkjJT5/dxLL9XmAhCYIgA6cr4D8nRQvkwcVN9W2XgBk/lewymFfIqgM7gRAu1EHoevez897jwq92GHcqAS8vdAcqHr1wl13V4SyX4xyueXCgKPjCYJjcmmW0Q/rbyrVYnMURLvCWQjDffMuSDKbjyCnzaI0zk3yuL/k1CXJZoZ20DueYc0Fz8xJV8nrBxUzHMGx+a1sqjA/8RJgLLKhqRVpytCdhbRlRCJ9gpdgFoqjqYqlIDoKBudZHi9o/KgEKGAjDY=
sudo: required
before_script:
- sudo pip install 'requests[security]' awscli
- "$TRAVIS_BUILD_DIR/tools/install_packages.sh $TOOLS_DIR"
script:
- cd $TRAVIS_BUILD_DIR/packer
- packer build webapp.json | tee /tmp/packer.out
- AMI=`awk -F':' '/(eu|us|ap|sa)-(west|central|east|northeast|southeast)-(1|2): ami-/ {print $2}' /tmp/packer.out |  tr -d '[[:space:]]'`
- cd $TRAVIS_BUILD_DIR/webapp
- terraform plan -var ami_id=$AMI && terraform apply -var ami_id=$AMI
